### PR TITLE
Update index.html copy

### PR DESCRIPTION
**Pull request by kandebonfim**
Just fixed some issues in the copy.

### CODE REVIEW

**Comment by kandebonfim** [comment]
I also removed the `Do you want my PDF CV? Just click the button <3` because it seems very redundant.

**Comment by jeanbauer** [comment]
Hey, Victor, keep the good work 🔝 

I don't want to create another PR to solve something so _tiny_. In the contact form, change "**promisse**" to "**promise**".

Cheers.

**Comment by kandebonfim** [comment]
@jeanbauer nice! [Just did it](https://github.com/victorjordan95/victorjordan95.github.io/pull/1/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL323)!

**Comment by victorjordan95** [comment]
Thank you guys! @kandebonfim @jeanbauer :D

**Pull request merged**
